outputs:
  - package:
      name: foo
      version: 0.0.1

    build:
      # Not `noarch: python` or `version_independent: true`, simulating arch- and python-versions specific builds
      string: ${{ python }}
      script:
        - mkdir -p "$PREFIX/lib/python$PY_VER/site-packages/foo"
        - cp "$HOME/foo/helpers.py" "$PREFIX/lib/python$PY_VER/site-packages/foo/helpers.py"

    requirements:
      #host:
      #  - python
      run:
        - python
        - requests

    tests:
      - python:
          imports:
            # Fails, always uses the latest python. This means the variant restriction is not being applied.
            # Uncommenting the `host` section above makes this pass.
            - foo.helpers
